"""LLM module: provider factory, model discovery, chat-model construction."""

from .factory import (
    ANTHROPIC_FALLBACK_MODELS,
    GEMINI_FALLBACK_MODELS,
    HUGGINGFACE_FALLBACK_MODELS,
    OLLAMA_FALLBACK_MODELS,
    OPENAI_FALLBACK_MODELS,
    XAI_FALLBACK_MODELS,
    LLMProviderError,
    build_chat_model,
    fallback_models,
    list_models,
)
from .pricing import (
    DEFAULT_PRICING_RULES,
    MODEL_PRICING,
    CostBreakdown,
    ModelPricing,
    PricingRule,
    PricingUnavailableError,
    RequestMode,
    UsageRecord,
    calculate_cost,
    effective_pricing_rule,
    estimate_model_cost,
)

__all__ = [
    "ANTHROPIC_FALLBACK_MODELS",
    "DEFAULT_PRICING_RULES",
    "GEMINI_FALLBACK_MODELS",
    "HUGGINGFACE_FALLBACK_MODELS",
    "MODEL_PRICING",
    "OLLAMA_FALLBACK_MODELS",
    "OPENAI_FALLBACK_MODELS",
    "XAI_FALLBACK_MODELS",
    "CostBreakdown",
    "LLMProviderError",
    "ModelPricing",
    "PricingRule",
    "PricingUnavailableError",
    "RequestMode",
    "UsageRecord",
    "build_chat_model",
    "calculate_cost",
    "effective_pricing_rule",
    "estimate_model_cost",
    "fallback_models",
    "list_models",
]
